<a href="https://colab.research.google.com/github/NagRaaz/A2/blob/master/mathops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [4]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [6]:
a

array([ 2,  7,  1, 99,  4])

In [7]:
b

array([ 12,  17,  11, 199,  14])

In [8]:
a[0]

2

In [9]:
b[0]

12

In [10]:
a+b

array([ 14,  24,  12, 298,  18])

In [11]:
a+2

array([  4,   9,   3, 101,   6])

In [12]:
a+a

array([  4,  14,   2, 198,   8])

In [13]:
a*2

array([  4,  14,   2, 198,   8])

In [14]:
a**2

array([   4,   49,    1, 9801,   16])